# configuration file for TravisCI


# Notes:
#  - you can skip a build by adding [ci skip] to the commit message

# see http://about.travis-ci.org/docs/user/languages/java/
language: java

# test for these JDK versions and environments
jdk:
#  - oraclejdk8
#  - oraclejdk7
  - openjdk7

# only build these branches (RegEx is also valid, eg. /^deploy.*$/):
branches:
  only:
    - master
    - deploy

# container-based build:
sudo: false


#--------------------------------------------------------------------
# script:
# install, bulid, test, ...
#--------------------------------------------------------------------

#before_install

# install imflux.jar (our own streaming library)
# Unveiled-Server was installed before in this directory: SAS-Systems/Unveiled-Server
# we install imflux to: SAS-Systems/inmflux (but actually does not matter)
before_script:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/SAS-Systems/imflux.git SAS-Systems/imflux
  - cd imflux
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B
  - cd ../Unveiled-Server

# build project
# run test reports and send to coveralls
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn clean test jacoco:report coveralls:report

# analyse code quality with sonarqube and send to server
after_success:
  - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL

#after_failure:

#before_deploy:


#--------------------------------------------------------------------
# deployment
#--------------------------------------------------------------------

deploy:
  skip_cleanup: true

#after_deploy:

# finally deploy Unveiled-Server.war to our server
#after_script:
#  - mvn tomcat7:deploy -Ddeploy.url=$DEPLOY_URL -Ddeploy.username=$DEPLOY_USER -Ddeploy.password=$DEPLOY_PASSWORD
